// <auto-generated />
#nullable enable annotations
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public static partial class DeepCloningMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public static partial global::Riok.Mapperly.IntegrationTests.Models.IdObject Copy(global::Riok.Mapperly.IntegrationTests.Models.IdObject src)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Models.IdObject();
            target.IdValue = src.IdValue;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public static partial global::Riok.Mapperly.IntegrationTests.Models.TestObject Copy(global::Riok.Mapperly.IntegrationTests.Models.TestObject src)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Models.TestObject(src.CtorValue, ctorValue2: src.CtorValue2)
            {
                IntInitOnlyValue = src.IntInitOnlyValue,
                RequiredValue = src.RequiredValue,
            };
            target.IntValue = src.IntValue;
            target.StringValue = src.StringValue;
            target.RenamedStringValue = src.RenamedStringValue;
            target.Flattening = Copy(src.Flattening);
            if (src.NullableFlattening != null)
            {
                target.NullableFlattening = Copy(src.NullableFlattening);
            }
            else
            {
                target.NullableFlattening = null;
            }
            target.UnflatteningIdValue = src.UnflatteningIdValue;
            target.NullableUnflatteningIdValue = src.NullableUnflatteningIdValue;
            if (src.NestedNullable != null)
            {
                target.NestedNullable = MapToTestObjectNested(src.NestedNullable);
            }
            else
            {
                target.NestedNullable = null;
            }
            if (src.NestedNullableTargetNotNullable != null)
            {
                target.NestedNullableTargetNotNullable = MapToTestObjectNested(src.NestedNullableTargetNotNullable);
            }
            else
            {
                target.NestedNullableTargetNotNullable = null;
            }
            if (src.NestedMember != null)
            {
                target.NestedMember = MapToTestObjectNestedMember(src.NestedMember);
            }
            else
            {
                target.NestedMember = null;
            }
            target.StringNullableTargetNotNullable = src.StringNullableTargetNotNullable;
            if (src.TupleValue != null)
            {
                target.TupleValue = MapToValueTupleOfStringAndString(src.TupleValue.Value);
            }
            else
            {
                target.TupleValue = null;
            }
            if (src.RecursiveObject != null)
            {
                target.RecursiveObject = Copy(src.RecursiveObject);
            }
            else
            {
                target.RecursiveObject = null;
            }
            if (src.SourceTargetSameObjectType != null)
            {
                target.SourceTargetSameObjectType = Copy(src.SourceTargetSameObjectType);
            }
            else
            {
                target.SourceTargetSameObjectType = null;
            }
            if (src.NullableReadOnlyObjectCollection != null)
            {
                target.NullableReadOnlyObjectCollection = MapToTestObjectNestedArray(src.NullableReadOnlyObjectCollection);
            }
            else
            {
                target.NullableReadOnlyObjectCollection = null;
            }
            target.MemoryValue = src.MemoryValue.Span.ToArray();
            target.StackValue = new global::System.Collections.Generic.Stack<string>(global::System.Linq.Enumerable.Reverse(src.StackValue));
            target.QueueValue = new global::System.Collections.Generic.Queue<string>(src.QueueValue);
            target.ImmutableArrayValue = src.ImmutableArrayValue;
            target.ImmutableListValue = src.ImmutableListValue;
            target.ImmutableQueueValue = src.ImmutableQueueValue;
            target.ImmutableStackValue = src.ImmutableStackValue;
            target.ImmutableSortedSetValue = src.ImmutableSortedSetValue;
            target.ImmutableDictionaryValue = src.ImmutableDictionaryValue;
            target.ImmutableSortedDictionaryValue = src.ImmutableSortedDictionaryValue;
            foreach (var item in src.ExistingISet)
            {
                target.ExistingISet.Add(item);
            }
            foreach (var item1 in src.ExistingHashSet)
            {
                target.ExistingHashSet.Add(item1);
            }
            foreach (var item2 in src.ExistingSortedSet)
            {
                target.ExistingSortedSet.Add(item2);
            }
            target.ExistingList.Capacity = src.ExistingList.Count + target.ExistingList.Count;
            foreach (var item3 in src.ExistingList)
            {
                target.ExistingList.Add(item3);
            }
            target.ISet = global::System.Linq.Enumerable.ToHashSet(src.ISet);
            target.HashSet = global::System.Linq.Enumerable.ToHashSet(src.HashSet);
            target.SortedSet = new global::System.Collections.Generic.SortedSet<string>(src.SortedSet);
            target.EnumValue = src.EnumValue;
            target.FlagsEnumValue = src.FlagsEnumValue;
            target.EnumName = src.EnumName;
            target.EnumRawValue = src.EnumRawValue;
            target.EnumStringValue = src.EnumStringValue;
            target.EnumReverseStringValue = src.EnumReverseStringValue;
            if (src.SubObject != null)
            {
                target.SubObject = MapToInheritanceSubObject(src.SubObject);
            }
            else
            {
                target.SubObject = null;
            }
            target.DateTimeValue = src.DateTimeValue;
            target.DateTimeValueTargetDateOnly = src.DateTimeValueTargetDateOnly;
            target.DateTimeValueTargetTimeOnly = src.DateTimeValueTargetTimeOnly;
            target.ToByteArrayWithInstanceMethod = src.ToByteArrayWithInstanceMethod;
            if (src.WithCreateMethod != null)
            {
                target.WithCreateMethod = global::Riok.Mapperly.IntegrationTests.Models.ConvertWithStaticMethodObject.ToConvertWithStaticMethodObject(src.WithCreateMethod);
            }
            else
            {
                target.WithCreateMethod = null;
            }
            if (src.WithCreateFromMethod != null)
            {
                target.WithCreateFromMethod = global::Riok.Mapperly.IntegrationTests.Models.ConvertWithStaticMethodObject.ToConvertWithStaticMethodObject(src.WithCreateFromMethod);
            }
            else
            {
                target.WithCreateFromMethod = null;
            }
            if (src.WithFromSingleMethod != null)
            {
                target.WithFromSingleMethod = global::Riok.Mapperly.IntegrationTests.Models.ConvertWithStaticMethodObject.ToConvertWithStaticMethodObject(src.WithFromSingleMethod);
            }
            else
            {
                target.WithFromSingleMethod = null;
            }
            if (src.WithCreateParamsMethod != null)
            {
                target.WithCreateParamsMethod = global::Riok.Mapperly.IntegrationTests.Models.ConvertWithStaticMethodObject.ToConvertWithStaticMethodObject(src.WithCreateParamsMethod);
            }
            else
            {
                target.WithCreateParamsMethod = null;
            }
            if (src.WithCreateFromParamsMethod != null)
            {
                target.WithCreateFromParamsMethod = global::Riok.Mapperly.IntegrationTests.Models.ConvertWithStaticMethodObject.ToConvertWithStaticMethodObject(src.WithCreateFromParamsMethod);
            }
            else
            {
                target.WithCreateFromParamsMethod = null;
            }
            if (src.WithFromShortParamsMethod != null)
            {
                target.WithFromShortParamsMethod = global::Riok.Mapperly.IntegrationTests.Models.ConvertWithStaticMethodObject.ToConvertWithStaticMethodObject(src.WithFromShortParamsMethod);
            }
            else
            {
                target.WithFromShortParamsMethod = null;
            }
            if (src.WithToDecimalMethod != null)
            {
                target.WithToDecimalMethod = global::Riok.Mapperly.IntegrationTests.Models.ConvertWithStaticMethodObject.ToConvertWithStaticMethodObject(src.WithToDecimalMethod);
            }
            else
            {
                target.WithToDecimalMethod = null;
            }
            target.SumComponent1 = src.SumComponent1;
            target.SumComponent2 = src.SumComponent2;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        private static global::Riok.Mapperly.IntegrationTests.Models.TestObjectNested MapToTestObjectNested(global::Riok.Mapperly.IntegrationTests.Models.TestObjectNested source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Models.TestObjectNested();
            target.IntValue = source.IntValue;
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        private static global::Riok.Mapperly.IntegrationTests.Models.TestObjectNestedMember MapToTestObjectNestedMember(global::Riok.Mapperly.IntegrationTests.Models.TestObjectNestedMember source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Models.TestObjectNestedMember();
            target.NestedMemberId = source.NestedMemberId;
            if (source.NestedMemberObject != null)
            {
                target.NestedMemberObject = MapToTestObjectNested(source.NestedMemberObject);
            }
            else
            {
                target.NestedMemberObject = null;
            }
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        private static (string A, string) MapToValueTupleOfStringAndString((string A, string) source)
        {
            var target = (A: source.A, source.Item2);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        private static global::Riok.Mapperly.IntegrationTests.Models.TestObjectNested[] MapToTestObjectNestedArray(global::System.Collections.Generic.IReadOnlyCollection<global::Riok.Mapperly.IntegrationTests.Models.TestObjectNested> source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Models.TestObjectNested[source.Count];
            var i = 0;
            foreach (var item in source)
            {
                target[i] = MapToTestObjectNested(item);
                i++;
            }
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        private static global::Riok.Mapperly.IntegrationTests.Models.InheritanceSubObject MapToInheritanceSubObject(global::Riok.Mapperly.IntegrationTests.Models.InheritanceSubObject source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Models.InheritanceSubObject();
            target.SubIntValue = source.SubIntValue;
            target.BaseIntValue = source.BaseIntValue;
            return target;
        }
    }
}