// <auto-generated />
#nullable enable
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public partial class BaseMapper
    {
        public virtual partial long IntToLong(int value)
        {
            return (long)value;
        }

        public partial short IntToShort(int value)
        {
            return (short)value;
        }
    }
}