// <auto-generated />
#nullable enable
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public partial class DerivedMapper
    {
        public override partial long IntToLong(int value)
        {
            return (long)value;
        }
    }
}