// <auto-generated />
#nullable enable
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public partial class DerivedMapper2
    {
        public sealed override partial long IntToLong(int value)
        {
            return (long)value;
        }

        public new partial short IntToShort(int value)
        {
            return (short)value;
        }
    }
}