// <auto-generated />
#nullable enable
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public partial class MappingTargetOriginalValueMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public partial global::Riok.Mapperly.IntegrationTests.Dto.OptionalDto MapToDto(global::Riok.Mapperly.IntegrationTests.Models.OptionalObject source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Dto.OptionalDto();
            target.Name = FromOptional(source.Name, target.Name);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public partial void UpdateDto(global::Riok.Mapperly.IntegrationTests.Dto.OptionalDto dto, global::Riok.Mapperly.IntegrationTests.Models.OptionalObject source)
        {
            dto.Name = FromOptional(source.Name, dto.Name);
        }
    }
}