// <auto-generated />
#nullable enable annotations
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public partial record NestedTestMapperRecord
    {
        public partial record TestNesting
        {
            public static partial class NestedMapper
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
                public static partial decimal ToDecimal(int value)
                {
                    return (decimal)value;
                }
            }
        }
    }
}