// <auto-generated />
#nullable enable
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public partial class UseExternalInstanceMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public partial global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto Map(global::Riok.Mapperly.IntegrationTests.Models.IdObject source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = _myOtherMapper.MapInt(source.IdValue);
            return target;
        }
    }
}