// <auto-generated />
#nullable enable
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public static partial class UseExternalMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public static partial global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto Map(global::Riok.Mapperly.IntegrationTests.Models.IdObject source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::Riok.Mapperly.IntegrationTests.Mapper.UseExternalMapper.MyOtherMapper.MapInt(source.IdValue);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public static partial global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto MapExternal(global::Riok.Mapperly.IntegrationTests.Models.IdObject source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::Riok.Mapperly.IntegrationTests.Mapper.ExternalMapper.MapStatic(source.IdValue);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public static partial global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto MapFromSourceExternal(global::Riok.Mapperly.IntegrationTests.Models.IdObject source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::Riok.Mapperly.IntegrationTests.Mapper.ExternalMapper.ComputeSumStatic(source);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public static partial global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto ConstantMapExternal(global::Riok.Mapperly.IntegrationTests.Models.IdObject source)
        {
            var target = new global::Riok.Mapperly.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::Riok.Mapperly.IntegrationTests.Mapper.ExternalMapper.IntValueStatic();
            return target;
        }
    }
}