// <auto-generated />
#nullable enable
namespace Riok.Mapperly.IntegrationTests.Mapper
{
    public static partial class UseUserMethodWithRef
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public static partial void Merge(global::Riok.Mapperly.IntegrationTests.Models.ArrayObject target, global::Riok.Mapperly.IntegrationTests.Models.ArrayObject second)
        {
            var MapArrayTargetRef = target.IntArray;
            MapArray(ref MapArrayTargetRef, second.IntArray);
            target.IntArray = MapArrayTargetRef;
        }
    }
}
