//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    private partial global::A Map(global::System.Collections.Generic.IDictionary<string, int> source)
    {
        // Could not generate mapping
        throw new System.NotImplementedException();
    }
}