//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(source))]
    partial global::B? Map(global::A? source)
    {
        if (source == null)
            return default;
        var target = new global::B();
        if (source.Value != null)
        {
            target.Value = MapToDictionaryOfStringAndString(source.Value);
        }
        else
        {
            target.Value = null;
        }
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private global::System.Collections.Generic.Dictionary<string, string?> MapToDictionaryOfStringAndString(global::System.Collections.Generic.IReadOnlyDictionary<string, string?> source)
    {
        var target = new global::System.Collections.Generic.Dictionary<string, string?>(source.Count);
        foreach (var item in source)
        {
            target[item.Key] = item.Value == null ? default : item.Value;
        }
        return target;
    }
}