//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BList Map(global::AList source)
    {
        var target = new global::BList(MapToListOfD(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BListAgain Map(global::AListAgain source)
    {
        var target = new global::BListAgain(MapToListOfD(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BReadOnlyCollection Map(global::AList source)
    {
        var target = new global::BReadOnlyCollection(MapToDArray(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BCustomCollection Map(global::AList source)
    {
        var target = new global::BCustomCollection(MapToCustomCollectionOfD(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BCollection Map(global::AList source)
    {
        var target = new global::BCollection(MapToListOfD(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BReadOnlyCollection Map(global::AReadOnlyCollection source)
    {
        var target = new global::BReadOnlyCollection(MapToDArray(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BCustomCollection Map(global::ACustomReadOnlyCollection source)
    {
        var target = new global::BCustomCollection(MapToCustomCollectionOfD(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BCollection Map(global::ACollection source)
    {
        var target = new global::BCollection(MapToListOfD1(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::BCustomCollection Map(global::ACustomCollection source)
    {
        var target = new global::BCustomCollection(MapToCustomCollectionOfD1(source.Values));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private global::D MapToD(global::C source)
    {
        var target = new global::D(source.Value);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private global::System.Collections.Generic.List<global::D> MapToListOfD(global::System.Collections.Generic.IReadOnlyCollection<global::C> source)
    {
        var target = new global::System.Collections.Generic.List<global::D>(source.Count);
        foreach (var item in source)
        {
            target.Add(MapToD(item));
        }
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private global::D[] MapToDArray(global::System.Collections.Generic.IReadOnlyCollection<global::C> source)
    {
        var target = new global::D[source.Count];
        var i = 0;
        foreach (var item in source)
        {
            target[i] = MapToD(item);
            i++;
        }
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private global::CustomCollection<global::D> MapToCustomCollectionOfD(global::System.Collections.Generic.IReadOnlyCollection<global::C> source)
    {
        var target = new global::CustomCollection<global::D>();
        foreach (var item in source)
        {
            target.Add(MapToD(item));
        }
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private global::System.Collections.Generic.List<global::D> MapToListOfD1(global::System.Collections.Generic.ICollection<global::C> source)
    {
        var target = new global::System.Collections.Generic.List<global::D>(source.Count);
        foreach (var item in source)
        {
            target.Add(MapToD(item));
        }
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private global::CustomCollection<global::D> MapToCustomCollectionOfD1(global::System.Collections.Generic.ICollection<global::C> source)
    {
        var target = new global::CustomCollection<global::D>();
        foreach (var item in source)
        {
            target.Add(MapToD(item));
        }
        return target;
    }
}