//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    private partial global::System.Collections.Generic.IList<global::B?>? Map(global::System.Collections.Generic.IList<global::A?>? source)
    {
        if (source == null)
            return default;
        var target = new global::System.Collections.Generic.List<global::B?>(source.Count);
        foreach (var item in source)
        {
            target.Add(MapToB(item));
        }
        return target;
    }

    private global::B? MapToB(global::A? source)
    {
        if (source == null)
            return default;
        var target = new global::B(source.V);
        return target;
    }
}