//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::E2[] Map(global::E1[] source)
    {
        var target = new global::E2[source.Length];
        for (var i = 0; i < source.Length; i++)
        {
            target[i] = (global::E2)source[i] is global::E2.A or global::E2.B or global::E2.C ? (global::E2)source[i] : throw new System.ArgumentOutOfRangeException(nameof(source), source[i], "The value of enum E1 is not supported");
        }
        return target;
    }
}