//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private partial global::System.Collections.Generic.List<string> Map(int[] source)
    {
        var target = new global::System.Collections.Generic.List<string>(source.Length);
        foreach (var item in source)
        {
            target.Add(item.ToString());
        }
        return target;
    }
}