//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::System.Linq.Expressions.Expression<global::System.Func<global::A?, global::B?>?>? Map()
    {
#nullable disable
        return x => new global::B(x.Value);
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(source))]
    private partial global::B? MapPrivate(global::A? source)
    {
        if (source == null)
            return default;
        var target = new global::B(source.Value);
        return target;
    }
}