//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::System.Linq.Expressions.Expression<global::System.Func<global::A?, global::B?>?>? Map()
    {
#nullable disable
        return x => new global::B(x.Value);
#nullable enable
    }
}