//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    static partial void MapToB(this global::B target, global::A source)
    {
        target.Value = source.Value;
    }
}