//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    static partial global::B MapToB(this global::A source)
    {
        var target = new global::B();
        target.Value = source.Value;
        return target;
    }
}
