//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    private partial global::D Map(global::A src, int value)
    {
        var target = new global::D();
        target.Nested = MapToE(src.Nested, value);
        return target;
    }

    private partial global::D Map(global::B src, int value)
    {
        var target = new global::D();
        target.Nested = MapToE1(src.Nested, value);
        return target;
    }

    private global::E MapToE(global::C source, int value)
    {
        var target = new global::E()
        {
            Name = source.Name,
            Value = value.ToString()
        };
        return target;
    }

    private global::E MapToE1(global::C source, int value)
    {
        var target = new global::E()
        {
            Name = source.Name,
            Value = value.ToString()
        };
        return target;
    }
}
