//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::B MapOther(global::A source)
    {
        var target = new global::B();
        target.Id = source.Value.Id;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::B Map(global::A source)
    {
        var target = new global::B();
        target.Id = source.Value.Id;
        return target;
    }
}