//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B MapOther(global::A a)
    {
        var target = new global::B();
        target.Value = a.Value.ToString("X");
        target.Value2 = a.Value2.ToString();
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B MapOther2(global::A a)
    {
        var target = new global::B();
        target.Value = a.Value.ToString();
        target.Value2 = a.Value2.ToString("D");
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B Map(global::A a)
    {
        var target = new global::B();
        target.Value = a.Value.ToString("X");
        target.Value2 = a.Value2.ToString("D");
        return target;
    }
}