//HintName: TestMapper.g.cs
// <auto-generated />
#nullable enable
public static partial class TestMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::B MapAnother(global::A a)
    {
        var target = new global::B();
        target.DestinationName = a.SourceName;
        return target;
    }
}