//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::B OtherMapper(global::A source)
    {
        var target = new global::B();
        target.Price = source.Price.ToString("C", _enCulture);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::B Mapper(global::A source)
    {
        var target = new global::B();
        target.Price = source.Price.ToString("C", _enCulture);
        return target;
    }
}