//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    static partial global::B Map(global::A a)
    {
        var target = new global::B();
        target.DestinationName = a.SourceName;
        return target;
    }
}