//HintName: CarMapper.g.cs
// <auto-generated />
#nullable enable
public partial class CarMapper
{
    static partial global::B Map(global::A a)
    {
        var target = CreateB();
        target.StringValue = a.StringValue;
        return target;
    }
}
