//HintName: CarMapper.g.cs
// <auto-generated />
#nullable enable
public partial class CarMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    static partial global::B Map(global::A a)
    {
        var target = CreateB();
        target.StringValue = a.StringValue;
        return target;
    }
}