//HintName: CarFeature.Mappers.CarMapper.g.cs
// <auto-generated />
#nullable enable
public static partial class CarFeature
{
    public partial class Mappers
    {
        public partial class CarMapper
        {
            static partial int ToInt(double value)
            {
                return (int)value;
            }
        }
    }
}
