//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    static partial global::B Map(global::A source)
    {
        var target = new global::B(global::OtherMapper.ToBExternal(source.Value));
        return target;
    }
}
