//HintName: CarMapper.g.cs
// <auto-generated />
#nullable enable
public partial class CarMapper
{
    static partial global::D MapToD(global::A value)
    {
        var target = new global::D(MapToE(value.Value1));
        return target;
    }

    private static global::E MapToE(global::B source)
    {
        var target = new global::E(MapToF(source.Value2));
        return target;
    }
}
