//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::ParentDomain Map(global::ParentDto parent, global::ChildDomain child)
    {
        var target = new global::ParentDomain();
        return target;
    }
}