//HintName: FooBarMapper.g.cs
// <auto-generated />
#pragma warning disable CS0618
#nullable enable
namespace Test.A
{
    internal partial class FooBarMapper
    {
        internal partial string FooToBar(string value)
        {
            return value;
        }
    }
}