//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial void Map(global::ParentDto parent, global::ParentDomain target, string parentId)
    {
        target.Id = parentId;
    }
}