//HintName: FooBarMapper1.g.cs
// <auto-generated />
#nullable enable
namespace Test.B
{
    internal partial class FooBarMapper
    {
        internal partial string FooToBar(string value)
        {
            return value;
        }
    }
}