//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    internal static partial global::B Map(global::A source)
    {
        var target = new global::B(global::Some.Namespace.OtherMapper.NewValue());
        return target;
    }
}