//HintName: A.Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class A
{
    internal partial class Mapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        public partial global::A Clone(global::A source)
        {
            var target = new global::A();
            target._value = source._value;
            return target;
        }
    }
}