//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
namespace MapperNamespace
{
    public partial class Mapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        partial global::MapperNamespace.B Map(global::MapperNamespace.A source)
        {
            var target = new global::MapperNamespace.B();
            target.FullName = global::OtherNamespace.OtherMapper.ToFullName(source);
            return target;
        }
    }
}