//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B Map(global::A src, int multiplier, string prefix)
    {
        var target = new global::B();
        target.ProcessedValue = ProcessValueWithPrefix(src.Value, multiplier, prefix);
        target.Value = src.Value;
        target.Multiplier = multiplier;
        target.Prefix = prefix;
        return target;
    }
}