//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial global::ADest? Map(global::A? source)
    {
        if (source == null)
            return default;
        var target = new global::ADest(source.Prop);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial global::BDest MapToDestinationB(global::B source)
    {
        var target = new global::BDest(MapToListOfInt32(source.Prop));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private static global::System.Collections.Generic.List<int> MapToListOfInt32(global::System.Collections.Generic.IReadOnlyCollection<int?> source)
    {
        var target = new global::System.Collections.Generic.List<int>(source.Count);
        foreach (var item in source)
        {
            target.Add(item ?? throw new System.ArgumentNullException(nameof(item)));
        }
        return target;
    }
}