//HintName: A.Mapper.g.cs
// <auto-generated />
#pragma warning disable CS0618
#nullable enable
public partial class A
{
    internal partial class Mapper
    {
        public partial global::A Clone(global::A source)
        {
            var target = new global::A();
            target._value = source._value;
            return target;
        }
    }
}