//HintName: A.Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class A
{
    internal partial class Mapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public partial global::A Clone(global::A source)
        {
            var target = new global::A();
            target.Value = source.Value;
            return target;
        }
    }
}