//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    private partial global::B Map(global::A source)
    {
        // Could not generate mapping
        throw new System.NotImplementedException();
    }
}