//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::B Map(global::A source)
    {
        var target = new global::B();
        DefaultMapping(source.Values, target.Values);
        MapV1(source.Values1, target.Values1);
        MapV2(source.Values2, target.Values2);
        return target;
    }
}