//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::B Map(global::A source)
    {
        var target = new global::B();
        if (source.Nested != null)
        {
            if (source.Nested.Value2 != null)
            {
                target.NestedValue2 = source.Nested.Value2.Value;
            }
            target.Nested = MapToD(source.Nested);
        }
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private global::D MapToD(global::C source)
    {
        var target = new global::D();
        if (source.Value1 != null)
        {
            target.Value1 = source.Value1.Value;
        }
        return target;
    }
}