//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::System.Linq.IQueryable<global::UserDto> ProjectToUserDto(global::System.Linq.IQueryable<global::User> src)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            src,
            x => new global::UserDto()
            {
                Roles = global::System.Linq.Enumerable.ToList(
                    global::System.Linq.Enumerable.Select(
                        global::System.Linq.Enumerable.Select(x.UserRoles, x1 => x1.Role),
                        x1 => new global::RoleDto()
                        {
                            Name = x1.Name,
                        }
                    )
                ),
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::UserDto MapToUserDto(global::User src)
    {
        var target = new global::UserDto();
        target.Roles = global::System.Linq.Enumerable.ToList(
            global::System.Linq.Enumerable.Select(
                global::System.Linq.Enumerable.Select(src.UserRoles, x1 => x1.Role),
                x => MapToRoleDto(x)
            )
        );
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private static global::RoleDto MapToRoleDto(global::Role source)
    {
        var target = new global::RoleDto();
        target.Name = source.Name;
        return target;
    }
}
