//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial void Map(global::A source, global::B target)
    {
        MapValues(MapToF(source.Value), target.Value);
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private global::F MapToF(global::C source)
    {
        var target = new global::F();
        target.Values = source.Values;
        return target;
    }
}