//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::System.Linq.IQueryable<global::B> Map(global::System.Linq.IQueryable<global::A> source, int multiplier)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            source,
            x => new global::B()
            {
                ProcessedValue = x.Nested.Value * multiplier,
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::B MapToB(global::A source, int multiplier)
    {
        var target = new global::B();
        target.ProcessedValue = ProcessValue(source.Nested.Value, multiplier);
        return target;
    }
}