//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    internal partial global::MyEntityDto MapToDto(global::MyEntity source)
    {
        var target = new global::MyEntityDto();
        target.Id = IntToInt(source.Id);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    internal partial global::System.Linq.IQueryable<global::MyEntityDto> ProjectToDto(global::System.Linq.IQueryable<global::MyEntity> source)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            source,
            x => new global::MyEntityDto()
            {
                Id = global::Extensions.WithOneAdded(x.Id),
            }
        );
#nullable enable
    }
}