//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    partial global::System.Linq.IQueryable<global::B> Map(global::System.Linq.IQueryable<global::A> source)
    {
        return System.Linq.Queryable.Select(source, MapToExpression());
    }

    private partial global::B MapPrivate(global::A source)
    {
        var target = new global::B()
        {
            Value = source.Value.ToString("C", null),
        };
        return target;
    }

    private global::System.Linq.Expressions.Expression<global::System.Func<global::A, global::B>> MapToExpression()
    {
#nullable disable
        return x => new global::B()
        {
            Value = x.Value.ToString("C", null),
        };
#nullable enable
    }
}