//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::System.Linq.IQueryable<global::B> Map(global::System.Linq.IQueryable<global::A> source)
    {
#nullable disable
        return System.Linq.Queryable.Select(source, x => new global::B()
        {
            Value = MapToDWithP(x.Value),
            Value2 = MapToDWithC(x.Value2),
            ValueDefault = new global::D(x.ValueDefault.Value.ToString("N")),
        });
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::B Map(global::A source)
    {
        var target = new global::B();
        target.Value = MapToDWithP(source.Value);
        target.Value2 = MapToDWithC(source.Value2);
        target.ValueDefault = MapToDDefault(source.ValueDefault);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::D MapToDWithP(global::C source)
    {
        var target = new global::D(source.Value.ToString("P"));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::D MapToDWithC(global::C source)
    {
        var target = new global::D(source.Value.ToString("C"));
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::D MapToDDefault(global::C source)
    {
        var target = new global::D(source.Value.ToString("N"));
        return target;
    }
}