//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::System.Linq.IQueryable<global::Target> Map(global::System.Linq.IQueryable<global::Source> source)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            source,
            x => new global::Target()
            {
                Id = x.Id,
                Result = ((global::IBase)x).Value,
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::Target Map(global::Source source)
    {
        var target = new global::Target();
        target.Id = source.Id;
        target.Result = MapResult((global::IBase)source);
        return target;
    }
}