//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::System.Linq.IQueryable<global::B> Map(global::System.Linq.IQueryable<global::A> source)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            source,
            x => new global::B()
            {
                Nested = new global::D { Value = global::System.Linq.Enumerable.FirstOrDefault(global::System.Linq.Enumerable.Select(x.Nested.Items, (x1, i) => x1 + i))},
            }
        );
#nullable enable
    }
}