//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::System.Linq.IQueryable<global::B> Map(global::System.Linq.IQueryable<global::A> source)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            source,
            x1 => new global::B()
            {
                Sum = a.Sources.Sum(x => x + x1.BaseValue),
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B Map(global::A source)
    {
        var target = new global::B()
        {
            Sum = CalcSum(source),
        };
        return target;
    }
}