//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::System.Linq.IQueryable<global::B> Map(global::System.Linq.IQueryable<global::A> src)
    {
#nullable disable
        return System.Linq.Queryable.Select(src, x => new global::B()
        {
            Parent = x.Parent != null ? new global::B()
            {
                Parent = x.Parent.Parent != null ? new global::B()
                {
                    Parent = x.Parent.Parent.Parent != null ? default : default,
                } : default,
            } : default,
        });
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B Map(global::A src)
    {
        var target = new global::B();
        if (src.Parent != null)
        {
            target.Parent = Map(src.Parent);
        }
        else
        {
            target.Parent = null;
        }
        return target;
    }
}