//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::System.Linq.IQueryable<global::B> Map(this global::System.Linq.IQueryable<global::A> query)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            query,
            x => new global::B()
            {
                Value = (decimal?)x.Value ?? 1,
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private static partial global::B Map(global::A src)
    {
        var target = new global::B();
        target.Value = (decimal?)MapValue(src.Value);
        return target;
    }
}