//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::System.Linq.IQueryable<global::D> Map(global::System.Linq.IQueryable<global::A> source)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(source, x => new global::D(new global::E(x.Value.Child.Name)));
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private static partial global::E Map(global::C source)
    {
        var target = new global::E(source.Name);
        return target;
    }
}