//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::System.Linq.IQueryable<global::B> Map(global::System.Linq.IQueryable<global::A> source, int additionalParameter)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            source,
            x => new global::B { StringValue = x.StringValue, AdditionalParameter = additionalParameter * 2 }
        );
#nullable enable
    }
}