//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private partial global::C Map(global::A source)
    {
        return MapToC(
            source,
            new global::Riok.Mapperly.Abstractions.ReferenceHandling.PreserveReferenceHandler()
        );
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private global::C MapToC(global::A source, global::Riok.Mapperly.Abstractions.ReferenceHandling.IReferenceHandler refHandler)
    {
        if (refHandler.TryGetReference<global::A, global::C>(source, out var existingTargetReference))
            return existingTargetReference;
        var target = new global::C()
        {
            Parent = MapToD(source.Parent, refHandler),
        };
        refHandler.SetReference<global::A, global::C>(source, target);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private global::D MapToD(global::B source, global::Riok.Mapperly.Abstractions.ReferenceHandling.IReferenceHandler refHandler)
    {
        if (refHandler.TryGetReference<global::B, global::D>(source, out var existingTargetReference))
            return existingTargetReference;
        var target = new global::D()
        {
            DeepParent = MapToC(source.DeepParent, refHandler),
        };
        refHandler.SetReference<global::B, global::D>(source, target);
        return target;
    }
}