//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::Product ToProduct(this global::ProductDTO source)
    {
        var target = new global::Product();
        target.Value = source.Value;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::ProductDTO ToDTO(this global::Product source)
    {
        var target = new global::ProductDTO();
        target.Value = source.Value;
        return target;
    }
}