//HintName: CarFeature.Mappers.CarMapper.g.cs
// <auto-generated />
#nullable enable
public static partial class CarFeature
{
    public static partial class Mappers
    {
        public partial class CarMapper
        {
            public partial global::B Map(global::A value)
            {
                var target = new global::B();
                target.SetValue(value.GetValue());
                return target;
            }
        }
            
        static file class UnsafeAccessor
        {
            [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "get_value")]
            public static extern int GetValue(this global::A source);

            [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_value")]
            public static extern void SetValue(this global::B target, int value);
        }
    }
}