//HintName: MyMapper.g.cs
// <auto-generated />
#nullable enable
public partial class MyMapper
{
    private partial global::B Map(global::A value)
    {
        var target = new global::B();
        return target;
    }
}