//HintName: MyMapper.g.cs
// <auto-generated />
#pragma warning disable CS0618
#nullable enable
public partial class MyMapper
{
    public partial object InstanceToObject(string s)
    {
        return (object)s;
    }
}