//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    private partial global::B Map(global::A s)
    {
        var target = new global::B();
        MapList(s.Value, target.Value);
        return target;
    }
}