//HintName: BaseMapper.g.cs
// <auto-generated />
#nullable enable
[global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
public class BaseMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::D BaseMapping(global::C source)
    {
        var target = new global::D(source.Value);
        return target;
    }
}