//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(src))]
    partial global::B? Map(global::A? src, int value)
    {
        if (src == null)
            return default;
        var target = new global::B();
        target.StringValue = src.StringValue;
        target.Value = value.ToString();
        return target;
    }
}