//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B Map(global::A src, int id)
    {
        var target = new global::B();
        target.Id = id;
        target.Name = src.Name;
        target.Nested = MapToBNested(src.Nested);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private global::BNested MapToBNested(global::ANested source)
    {
        var target = new global::BNested();
        target.Id = source.Id;
        target.Value = source.Value;
        return target;
    }
}