//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B Map(global::A src, int value)
    {
        var refHandler = new global::Riok.Mapperly.Abstractions.ReferenceHandling.PreserveReferenceHandler();
        if (refHandler.TryGetReference<global::A, global::B>(src, out var existingTargetReference))
            return existingTargetReference;
        var target = new global::B()
        {
            Value = value.ToString(),
        };
        refHandler.SetReference<global::A, global::B>(src, target);
        target.StringValue = src.StringValue;
        return target;
    }
}