//HintName: BaseMapper.g.cs
// <auto-generated />
#pragma warning disable CS0618
#nullable enable
public partial class BaseMapper
{
    protected partial short MyIntToShortMapping(int value)
    {
        return (short)value;
    }
}