//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    partial global::B Map(global::A src, int value)
    {
        var target = new global::B();
        target.StringValue = src.StringValue;
        target.Value = value.ToString();
        return target;
    }
}