//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::B Map(global::A src)
    {
        var target = new global::B();
        target.Value = StringToNullable(src.Value);
        target.NonNullableValue = StringToNonNullable(src.NonNullableValue);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public partial global::B Map(global::A src, string? extra)
    {
        var target = new global::B();
        target.Value = StringToNullable(src.Value);
        target.NonNullableValue = StringToNonNullable(src.NonNullableValue);
        target.Extra = StringToNullable(extra);
        return target;
    }
}