//HintName: Mapper.g.cs
// <auto-generated />
#pragma warning disable CS0618
#nullable enable
namespace MyCompany.MyMapper
{
    public partial class Mapper
    {
        private partial string Map(int source)
        {
            return source.ToString();
        }
    }
}