//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public static partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::System.Linq.IQueryable<global::CarDto> ProjectToCarDto(this global::System.Linq.IQueryable<global::Car> query)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            query,
            x => new global::CarDto()
            {
                Id = x.Id,
                CarName = x.Name,
                Maker = new global::MakerDto()
                {
                    Id = x.Make.Id,
                    MakerName = x.Make.Name,
                },
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::CarDto MapToCarDto(this global::Car car)
    {
        var target = new global::CarDto()
        {
            Id = car.Id,
            CarName = car.Name,
            Maker = global::OtherMapper.ToMakerDto(car.Make),
        };
        return target;
    }
}