//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    private partial (string A, string B) Map((int, int) src)
    {
        var target = (A: src.Item1.ToString(), B: src.Item2.ToString());
        return target;
    }

    private partial (string A, string B) Map((int B, int A) src)
    {
        var target = (A: src.A.ToString(), B: src.B.ToString());
        return target;
    }
}
