//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    private partial ((int, int D) C, int) Map(((int F, int G), string B) source)
    {
        var target = (C: MapToValueTuple(source.Item1), int.Parse(source.B));
        target.C.D = int.Parse(source.B);
        return target;
    }

    private (int, int D) MapToValueTuple((int F, int G) source)
    {
        var target = (source.F, D: source.G);
        return target;
    }
}